### ISSUE TITLE
Possible unhandled promise rejection (id: 0): TypeError: Network request failed

### ISSUE THREAD

**Issue by dijarvrella** [rbrki07/rn-expo-oauth-authorization-code-flow-pkce-keycloak#1]
Hi @rbrki07, 

First of all great work. Really inspiring!

Can you please provide some guidance as I can't make this run successfully.

It fails on with the following: `Possible unhandled promise rejection (id: 0): TypeError: Network request failed` and I believe that is due to useAutoDiscovery function not returning a valid discovery object of interface DiscoveryDocument.

Then if I try to type **_Sign in_** button I get `Possible unhandled promise rejection (id: 5): Error: Cannot prompt to authenticate until the request has finished loading.`

Fastest way to replicate the problem is:
1. clone your repo, 
`git clone git@github.com:rbrki07/rn-expo-oauth-authorization-code-flow-pkce-keycloak.git`
3. run the keycloak:
`docker run --name keycloak --detach --publish 11111:8080 --env KEYCLOAK_ADMIN=admin --env KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:latest start-dev`

I have configured keycloak same as you have it shown in your blog but I am attaching the realm export ran using:
`docker exec -it keycloak /opt/keycloak/bin/kc.sh export --file /tmp/realm-export.json --realm test --users realm_file`
[realm-export.json](https://github.com/rbrki07/rn-expo-oauth-authorization-code-flow-pkce-keycloak/files/14966926/realm-export.json)
4. run `npx expo start`
5. Scan the QR code from Android/iOS
6.  `Possible unhandled promise rejection (id: 0): TypeError: Network request failed` pops out

**Comment by rbrki07** [comment]
Hi @dijarvrella,
sounds like a network issue. Are you running the Expo app on a real device? If yes, the app won't find Keycloak running on http://localhost:11111/ on your development computer.

**Comment by dijarvrella** [comment]
Hi @rbrki07, thanks for the quick response.

I am running Expo app on my local machine. The Keycloak is also running on my local machine.

I made it all work I hardcoded discovery object as follows:

```
const discovery = {
    authorizationEndpoint:
      'http://192.168.0.87:11111/realms/test/protocol/openid-connect/auth',
    tokenEndpoint:
      'http://192.168.0.87:11111/realms/test/protocol/openid-connect/token',
    revocationEndpoint:
      'http://192.168.0.87:11111/realms/test/protocol/openid-connect/revoke',
    endSessionEndpoint:
      'http://192.168.0.87:11111/realms/test/protocol/openid-connect/logout',
    userInfoEndpoint:
      'http://192.168.0.87:11111/realms/test/protocol/openid-connect/userinfo',
  }
```
It looks to me the problem seems to be related with this useAutoDiscovery function.

the IP address there is my private IP on my localmachine but due to running expo app now with @expo/ngrok tunnel

**Comment by rbrki07** [comment]
Well, that's strange. I will try to reproduce your problem using the latest Expo SDK and module version.

**Comment by dijarvrella** [comment]
alright, I was able to resolve this by doing the following:

1. Update the env to use the IP of the interface rather than localhost`EXPO_PUBLIC_KEYCLOAK_URL='http://<interface_IP>:<keycloak_port>/realms/<realm_name>''`

Thanks for all the help and making this available for all.
